#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  4 21:37:25 2017

@author: nlhsueh
"""

import numpy as np 
x = np.float32(1.0) 
x

y = np.int_([1,2,4]) 
y

z = np.arange(3, dtype=np.uint8) 
z

x = np.array([12, 23, 34])
x
type(x)


a = np.random.random((2,3))
a *= a*100
print (a)

a.min(axis=0)
a.min(axis=1)
